### ISSUE TITLE
BootstrapHorizontalForm doesn't work properly

### ISSUE THREAD

**Issue by bsima** [ncaq/yesod-form-bootstrap4#1]
I'm pretty sure you need a `.row` added here: https://github.com/ncaq/yesod-form-bootstrap4/blob/8298c8a7e97065a2415e0aad101f289d93fce048/src/Yesod/Form/Bootstrap4.hs#L101

The relevant docs: https://getbootstrap.com/docs/4.1/components/forms/#horizontal-form

Without the `.row`, the label is shown above the input, instead of next to it.

**Comment by ncaq** [comment]
I solved it.
Please you check valid.

**Comment by bsima** [comment]
Thanks for the quick fix! :smiley:
