### ISSUE TITLE
New upload to hackage or remove .cabal from gitignore

### ISSUE THREAD

**Issue by goolord** [ncaq/yesod-form-bootstrap4#6]
https://github.com/ncaq/yesod-form-bootstrap4/blob/master/.gitignore#L1

I cannot build the latest commit of yesod-form-bootstrap4 with cabal because there is no .cabal file.

**Comment by ncaq** [comment]
Sorry for my late reply.
I use
[sol/hpack: hpack: A modern format for Haskell packages](https://github.com/sol/hpack)
I can use this package from Hackage.
What are you build ev?

**Comment by goolord** [comment]
Sorry, my initial comment may have been misleading.  I have a project that uses nix to manage its build environment. I needed the latest revision of yesod-form-bootstrap4, but it wasn't available on hackage and I couldn't use cabal2nix to generate the nix expression for this package because the .cabal file wasn't available. i have however learned that cabal2nix has an `--hpack` flag to generate the cabal file.
